#!/usr/bin/env bash
# felix — one command to a running stack.
#
#   ./start.sh
#
# Brings up everything end to end:
#   1. CockroachDB (Docker) — a persistent single node, auto-created + seeded
#   2. Python venv + dependencies, and a local-dev .env
#   3. Frontend dependencies + .env.local
#   4. The backend API (:8000) and the frontend dev server (:5173)
#
# Ctrl-C stops the API and frontend. The database keeps running in Docker
# (data persists in a named volume); stop it with `docker compose down`.
#
# Full manual walkthrough, the CDC demo, and troubleshooting live in SETUP.md.
set -euo pipefail

cd "$(dirname "$0")"

BOLD="$(printf '\033[1m')"; DIM="$(printf '\033[2m')"; RESET="$(printf '\033[0m')"
step() { echo "${BOLD}==> $*${RESET}"; }
info() { echo "${DIM}    $*${RESET}"; }
die()  { echo "${BOLD}error:${RESET} $*" >&2; exit 1; }

# --- 0. preflight --------------------------------------------------------------
step "Checking prerequisites"
command -v docker  >/dev/null 2>&1 || die "docker is required (https://docs.docker.com/get-docker/)"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required"
command -v python3 >/dev/null 2>&1 || die "python3 (3.10+) is required"
command -v npm     >/dev/null 2>&1 || die "node/npm (18+) is required"
info "docker, python3, npm found"

# --- 1. CockroachDB (Docker; auto-creates + seeds the felix DB) ----------------
step "Starting CockroachDB (Docker) — auto-creates + seeds the felix database"
docker compose up -d
info "waiting for the schema + seed step to finish (this is idempotent) ..."
deadline=$(( $(date +%s) + 180 ))
until docker compose exec -T crdb cockroach sql --insecure --host=localhost:26257 \
        --database=felix -e "SELECT count(*) FROM incidents" >/dev/null 2>&1; do
  [ "$(date +%s)" -lt "$deadline" ] || die "timed out waiting for CockroachDB to seed (see: docker compose logs crdb-init)"
  sleep 2
done
info "CockroachDB ready — SQL :26257, web console http://localhost:8080"

# --- 2. Python env + local .env ------------------------------------------------
step "Setting up the Python environment"
if [ ! -d .venv ]; then
  python3 -m venv .venv
  info "created .venv"
fi
./.venv/bin/pip install --quiet --upgrade pip
./.venv/bin/pip install --quiet -r requirements.txt
info "dependencies installed"

if [ ! -f .env ]; then
  cat > .env <<'ENV'
# Local-dev config generated by start.sh. Edit freely — this file is gitignored.
DATABASE_URL=postgresql://root@localhost:26257/felix?sslmode=disable
EMBED_PROVIDER=local
LLM_PROVIDER=gemini
# Reasoning (the /chat path) needs a key: https://aistudio.google.com/apikey
GEMINI_API_KEY=
GEMINI_MODEL_ID=gemini-flash-latest
# Run the CDC watcher + sample-traffic driver in-process (same as the deploy),
# so Live monitoring has data and the anomaly→auto-triage path is live locally.
FELIX_RUN_WATCHER=1
FELIX_RUN_SAMPLE=1
ENV
  info "wrote a local-dev .env"
else
  info ".env already exists — leaving it untouched"
fi

# The reasoning path (/chat) needs a Gemini key; recall + mock UI work without one.
if ! grep -Eq '^GEMINI_API_KEY=.+' .env; then
  echo "${DIM}    note: GEMINI_API_KEY is unset in .env — recall works, but diagnosis (/chat) will 503.${RESET}"
  echo "${DIM}          add a key from https://aistudio.google.com/apikey to enable it.${RESET}"
fi

# --- 3. Frontend ---------------------------------------------------------------
step "Setting up the frontend"
( cd frontend
  [ -d node_modules ] || npm install --silent
  [ -f .env.local ] || echo 'VITE_API_URL=http://localhost:8000' > .env.local
)
info "frontend ready"

# --- 4. Launch backend + frontend ----------------------------------------------
step "Starting the app"

# Run the CDC watcher + sample-traffic driver in-process (matches the deploy),
# so Live monitoring has data and the anomaly→auto-triage path is live. Exported
# here too — not just in the generated .env — so it applies even when a .env
# from an earlier run already exists (load_dotenv won't override the shell env).
export FELIX_RUN_WATCHER=1
export FELIX_RUN_SAMPLE=1

pids=()
cleanup() {
  echo
  step "Stopping API + frontend (database stays up — 'docker compose down' to stop it)"
  for pid in "${pids[@]:-}"; do kill "$pid" 2>/dev/null || true; done
  wait 2>/dev/null || true
}
trap cleanup INT TERM

./.venv/bin/python -m src serve --host 127.0.0.1 --port 8000 &
pids+=($!)
( cd frontend && npm run dev ) &
pids+=($!)

echo
echo "${BOLD}felix is starting:${RESET}"
echo "    API      → http://localhost:8000  (health: /health)"
echo "    frontend → http://localhost:5173"
echo "    DB       → CockroachDB in Docker (console http://localhost:8080)"
echo "${DIM}    Ctrl-C to stop the API + frontend.${RESET}"
echo
wait
